//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qwerty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSEREGISTRATION
    {
        public int Id { get; set; }
        public int Trainerid { get; set; }
        public int Courseid { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string IsDone { get; set; }
        public int TotalPoint { get; set; }
        public byte[] CertificateImage { get; set; }
        public string Comment { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual TRAINER TRAINER { get; set; }
    }
}
