CREATE DATABASE [Academy_fitness]
USE [Academy_fitness]
GO

CREATE TABLE [TRAINER](
[Id]						INT PRIMARY KEY IDENTITY(0,1)																		NOT NULL,
[Name]						NVARCHAR(50)																						NOT NULL,
)
GO

CREATE TABLE [COURSEREGISTRATION](
[Id]						INT PRIMARY KEY IDENTITY(0,1)			NOT NULL,
[Trainerid]					INT CONSTRAINT FK_COURSEREGISTRATION_TRAINERID_TRAINER_ID FOREIGN KEY REFERENCES [TRAINER] ([Id])	NOT NULL,
[Courseid]					INT CONSTRAINT FK_COURSEREGISTRATION_COURSEID_COURSE_ID FOREIGN KEY REFERENCES [COURSE] ([Id])		NOT NULL,
[CreatedDate]				DATE NOT NULL,
[IsDone]					NVARCHAR(10) NOT NULL,
[TotalPoint]				INT NOT NULL,
[CertificateImage]			IMAGE NULL,
[Comment]					NVARCHAR(100) NULL,
)
GO

CREATE TABLE [COURSE](
[Id]						INT PRIMARY KEY IDENTITY(0,1)																		NOT NULL,
[Title]						NVARCHAR(50)																						NOT NULL,
)
GO